--DROP ALL OBJECTS DELETE FILES;
DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS genre (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS mpa_rating (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(5)
);

CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    description VARCHAR(200),
    releaseDate DATE,
    mpa_id BIGINT,
    rate BIGINT,
    duration BIGINT,
    FOREIGN KEY(mpa_id) REFERENCES mpa_rating(id)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100),
    login VARCHAR(100),
    name VARCHAR(100),
    birthday DATE
);

CREATE TABLE IF NOT EXISTS films_genre (
    film_id BIGINT,
    genre_id BIGINT,
    FOREIGN KEY(film_id) REFERENCES films(id),
    FOREIGN KEY(genre_id) REFERENCES genre(id),
    PRIMARY KEY(film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS films_likes (
    film_id BIGINT,
    user_id BIGINT,
    FOREIGN KEY(film_id) REFERENCES films(id),
    FOREIGN KEY(user_id) REFERENCES users(id),
    PRIMARY KEY(film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friendship (
    user_id BIGINT,
    friend_id BIGINT,
    FOREIGN KEY(user_id) REFERENCES users(id),
    FOREIGN KEY(friend_id) REFERENCES users(id),
    PRIMARY KEY (user_id, friend_id)
);